import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
import plotly.express as px
import plotly.graph_objects as go
from datetime import date, timedelta
import warnings
import base64
warnings.filterwarnings("ignore")

st.set_page_config(page_title="QuantEdge | Portfolio Analytics", page_icon="📊", layout="wide", initial_sidebar_state="expanded")

# ─── TRANSLATIONS ───
T = {
    "en": {
        "brand_sub": "Portfolio Analytics Platform",
        "config": "PORTFOLIO CONFIGURATION",
        "tickers": "Ticker Symbols",
        "start": "Start Date",
        "end": "End Date",
        "risk_params": "RISK PARAMETERS",
        "risk_tolerance": "Risk Tolerance",
        "conservative": "Conservative",
        "balanced": "Balanced",
        "aggressive": "Aggressive",
        "profile": "Profile",
        "run": "▶  RUN ANALYSIS",
        "disclaimer": "QuantEdge v2.0 | Not financial advice",
        "title": "Portfolio",
        "title2": " Analytics Dashboard",
        "fetching": "Fetching market data...",
        "no_tickers": "No valid tickers found.",
        "could_not_load": "Could not load",
        "s1": "01 — Portfolio Metrics",
        "s2": "02 — Risk Analysis",
        "s3": "03 — Performance Charts",
        "s4": "04 — Portfolio Optimization",
        "s5": "05 — Investment Insights",
        "s6": "06 — Export Report",
        "ann_return": "Annualized Return",
        "volatility": "Volatility",
        "sharpe": "Sharpe Ratio",
        "sortino": "Sortino Ratio",
        "max_dd": "Max Drawdown",
        "corr_matrix": "Correlation Matrix",
        "ret_vol": "Return vs. Volatility",
        "cum_returns": "Cumulative Returns",
        "growth": "Growth of $1",
        "drawdown": "Drawdown Analysis",
        "opt_alloc": "Optimal Allocation",
        "alloc_10k": "Allocation $10K",
        "weight": "Weight",
        "increase": "▲ INCREASE EXPOSURE",
        "decrease": "▼ REDUCE / EXIT",
        "diversify": "◆ DIVERSIFY",
        "no_increase": "No assets flagged for increase.",
        "no_decrease": "No assets flagged for reduction.",
        "no_diversify": "Correlations within acceptable range.",
        "insight_increase": "Strong risk-adjusted returns with controlled volatility.",
        "insight_decrease": "Underperforming on risk-adjusted basis.",
        "insight_diversify": "High co-movement; consider diversifying.",
        "sharpe_lbl": "Sharpe",
        "vol_lbl": "Max DD",
        "avg_corr_lbl": "Avg correlation",
        "download_pdf": "⬇  DOWNLOAD PDF REPORT",
        "save_pdf": "📄 Save PDF Report",
        "generating_pdf": "Generating PDF...",
        "pdf_failed": "PDF failed. Run: pip install fpdf2",
        "pdf_title": "QuantEdge Portfolio Report",
        "pdf_period": "Period",
        "pdf_assets": "Assets",
        "pdf_metrics": "Portfolio Metrics",
        "pdf_alloc": "Optimal Allocation",
        "pdf_insights": "Investment Insights",
        "pdf_footer": "Generated by QuantEdge Analytics | Not financial advice",
        "ticker_col": "Ticker",
        "ann_return_col": "Ann. Return",
        "footer": "QUANTEDGE ANALYTICS · NOT FINANCIAL ADVICE",
        "landing_title": "Institutional-Grade Portfolio Analysis",
        "landing_sub": "Enter tickers and date range in the sidebar, then click RUN ANALYSIS.",
        "lang_label": "🌐 Language",
    },
    "fr": {
        "brand_sub": "Plateforme d'Analyse de Portefeuille",
        "config": "CONFIGURATION DU PORTEFEUILLE",
        "tickers": "Symboles Boursiers",
        "start": "Date de Début",
        "end": "Date de Fin",
        "risk_params": "PARAMÈTRES DE RISQUE",
        "risk_tolerance": "Tolérance au Risque",
        "conservative": "Conservateur",
        "balanced": "Équilibré",
        "aggressive": "Agressif",
        "profile": "Profil",
        "run": "▶  LANCER L'ANALYSE",
        "disclaimer": "QuantEdge v2.0 | Pas un conseil financier",
        "title": "Tableau de Bord",
        "title2": " Analytique",
        "fetching": "Récupération des données...",
        "no_tickers": "Aucun symbole valide trouvé.",
        "could_not_load": "Impossible de charger",
        "s1": "01 — Métriques du Portefeuille",
        "s2": "02 — Analyse des Risques",
        "s3": "03 — Graphiques de Performance",
        "s4": "04 — Optimisation du Portefeuille",
        "s5": "05 — Recommandations d'Investissement",
        "s6": "06 — Exporter le Rapport",
        "ann_return": "Rendement Annualisé",
        "volatility": "Volatilité",
        "sharpe": "Ratio de Sharpe",
        "sortino": "Ratio de Sortino",
        "max_dd": "Perte Maximale",
        "corr_matrix": "Matrice de Corrélation",
        "ret_vol": "Rendement vs. Volatilité",
        "cum_returns": "Rendements Cumulés",
        "growth": "Croissance de 1$",
        "drawdown": "Analyse des Pertes",
        "opt_alloc": "Allocation Optimale",
        "alloc_10k": "Allocation 10 000$",
        "weight": "Poids",
        "increase": "▲ AUGMENTER L'EXPOSITION",
        "decrease": "▼ RÉDUIRE / SORTIR",
        "diversify": "◆ DIVERSIFIER",
        "no_increase": "Aucun actif signalé pour augmentation.",
        "no_decrease": "Aucun actif signalé pour réduction.",
        "no_diversify": "Corrélations dans la plage acceptable.",
        "insight_increase": "Bons rendements ajustés au risque avec faible volatilité.",
        "insight_decrease": "Sous-performance sur base ajustée au risque.",
        "insight_diversify": "Fort co-mouvement; envisagez de diversifier.",
        "sharpe_lbl": "Sharpe",
        "vol_lbl": "Perte Max",
        "avg_corr_lbl": "Corrélation moyenne",
        "download_pdf": "⬇  TÉLÉCHARGER LE RAPPORT PDF",
        "save_pdf": "📄 Sauvegarder le Rapport PDF",
        "generating_pdf": "Génération du PDF...",
        "pdf_failed": "Échec PDF. Exécutez: pip install fpdf2",
        "pdf_title": "Rapport de Portefeuille QuantEdge",
        "pdf_period": "Période",
        "pdf_assets": "Actifs",
        "pdf_metrics": "Métriques du Portefeuille",
        "pdf_alloc": "Allocation Optimale",
        "pdf_insights": "Recommandations d'Investissement",
        "pdf_footer": "Généré par QuantEdge Analytics | Pas un conseil financier",
        "ticker_col": "Symbole",
        "ann_return_col": "Rend. Annualisé",
        "footer": "QUANTEDGE ANALYTICS · PAS UN CONSEIL FINANCIER",
        "landing_title": "Analyse de Portefeuille Institutionnelle",
        "landing_sub": "Entrez les symboles et la période dans la barre latérale, puis cliquez LANCER L'ANALYSE.",
        "lang_label": "🌐 Langue",
    }
}

st.markdown("""
<style>
html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
.stApp { background-color: #0a0e1a; }
section[data-testid="stSidebar"] { background: linear-gradient(180deg, #0d1117 0%, #111827 100%); border-right: 1px solid #1e2535; }
section[data-testid="stSidebar"] * { color: #c9d1e0 !important; }
.metric-card { background: linear-gradient(135deg, #111827 0%, #1a2236 100%); border: 1px solid #1e3a5f; border-radius: 12px; padding: 20px 24px; text-align: center; box-shadow: 0 4px 20px rgba(0,0,0,0.4); }
.metric-label { font-size: 11px; font-weight: 600; letter-spacing: 1.2px; text-transform: uppercase; color: #6b7fa3; margin-bottom: 8px; }
.metric-value { font-size: 28px; font-weight: 700; color: #e8eaf0; }
.metric-value.positive { color: #00d4a0; }
.metric-value.negative { color: #ff4d6d; }
.metric-value.neutral { color: #4da6ff; }
.section-header { font-size: 13px; font-weight: 700; letter-spacing: 2px; text-transform: uppercase; color: #4da6ff; border-bottom: 1px solid #1e2d45; padding-bottom: 10px; margin-bottom: 20px; }
.insight-increase { background: rgba(0,212,160,0.1); border-left: 3px solid #00d4a0; border-radius: 6px; padding: 12px 16px; margin: 8px 0; color: #c9d1e0; }
.insight-decrease { background: rgba(255,77,109,0.1); border-left: 3px solid #ff4d6d; border-radius: 6px; padding: 12px 16px; margin: 8px 0; color: #c9d1e0; }
.insight-diversify { background: rgba(77,166,255,0.1); border-left: 3px solid #4da6ff; border-radius: 6px; padding: 12px 16px; margin: 8px 0; color: #c9d1e0; }
.brand { font-size: 22px; font-weight: 800; color: #4da6ff; letter-spacing: 1px; }
.brand-sub { font-size: 10px; letter-spacing: 3px; color: #4a5568; text-transform: uppercase; }
hr { border-color: #1e2535; }
.stButton > button { background: linear-gradient(135deg, #1a4fa0 0%, #0d2d6b 100%); color: white; border: none; border-radius: 8px; font-weight: 600; padding: 10px 20px; width: 100%; }
</style>
""", unsafe_allow_html=True)

CHART_LAYOUT = dict(
    paper_bgcolor="#111827", plot_bgcolor="#0d1117",
    font=dict(family="Inter", color="#c9d1e0", size=12),
    xaxis=dict(gridcolor="#1e2535", linecolor="#1e2535"),
    yaxis=dict(gridcolor="#1e2535", linecolor="#1e2535"),
    margin=dict(l=50, r=30, t=50, b=50),
    legend=dict(bgcolor="rgba(0,0,0,0)", bordercolor="#1e2535")
)

@st.cache_data(show_spinner=False)
def download_data(tickers, start, end):
    raw = yf.download(tickers, start=start, end=end, auto_adjust=True, progress=False)
    if len(tickers) == 1:
        prices = raw[["Close"]].rename(columns={"Close": tickers[0]})
    else:
        prices = raw["Close"]
    prices.dropna(how="all", inplace=True)
    return prices

def compute_metrics(prices):
    returns = prices.pct_change().dropna()
    ann_return = (1 + returns.mean()) ** 252 - 1
    ann_vol = returns.std() * np.sqrt(252)
    rf = 0.05
    sharpe = (ann_return - rf) / ann_vol
    downside = returns.copy()
    downside[downside > 0] = 0
    ann_downside = downside.std() * np.sqrt(252)
    sortino = (ann_return - rf) / ann_downside
    cum = (1 + returns).cumprod()
    rolling_max = cum.cummax()
    drawdown = (cum - rolling_max) / rolling_max
    max_dd = drawdown.min()
    metrics = pd.DataFrame({
        "ann_return": ann_return, "volatility": ann_vol,
        "sharpe": sharpe, "sortino": sortino, "max_dd": max_dd,
    })
    return metrics, returns, cum, drawdown

def optimize_portfolio(returns, risk_tolerance=0.5):
    try:
        import cvxpy as cp
        mu = returns.mean().values * 252
        Sigma = returns.cov().values * 252
        n = len(mu)
        w = cp.Variable(n)
        lam = 1 - risk_tolerance
        objective = cp.Maximize(mu @ w - lam * cp.quad_form(w, Sigma))
        constraints = [cp.sum(w) == 1, w >= 0.02, w <= 0.60]
        prob = cp.Problem(objective, constraints)
        prob.solve(solver=cp.CLARABEL, warm_start=True)
        if prob.status in ["optimal", "optimal_inaccurate"]:
            weights = np.array(w.value)
            weights = np.clip(weights, 0, 1)
            weights /= weights.sum()
            return dict(zip(returns.columns, weights))
    except Exception:
        pass
    ann_return = returns.mean() * 252
    ann_vol = returns.std() * np.sqrt(252)
    sharpe = (ann_return - 0.05) / ann_vol
    sharpe_pos = sharpe.clip(lower=0.01)
    weights = sharpe_pos / sharpe_pos.sum()
    return dict(zip(returns.columns, weights.values))

def generate_insights(metrics, returns, t):
    insights = {"increase": [], "decrease": [], "diversify": []}
    n = len(metrics)
    corr = returns.corr()
    for ticker in metrics.index:
        s = metrics.loc[ticker, "sharpe"]
        v = metrics.loc[ticker, "volatility"]
        dd = metrics.loc[ticker, "max_dd"]
        avg_corr = corr[ticker].drop(ticker).mean() if n > 1 else 0
        if s > 1.0 and v < 0.30:
            insights["increase"].append(f"<b>{ticker}</b> — {t['sharpe_lbl']} {s:.2f} | Vol {v:.1%} | {t['insight_increase']}")
        elif s < 0.3 or dd < -0.35:
            insights["decrease"].append(f"<b>{ticker}</b> — {t['sharpe_lbl']} {s:.2f} | {t['vol_lbl']} {dd:.1%} | {t['insight_decrease']}")
        if n > 1 and avg_corr > 0.75:
            insights["diversify"].append(f"<b>{ticker}</b> — {t['avg_corr_lbl']} {avg_corr:.2f} | {t['insight_diversify']}")
    return insights

def make_pdf_report(tickers, start_date, end_date, metrics, weights, insights, t):
    try:
        from fpdf import FPDF
    except ImportError:
        return None
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(77, 166, 255)
    pdf.cell(0, 15, t["pdf_title"], ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 120)
    pdf.cell(0, 8, f"{t['pdf_period']}: {start_date} - {end_date}   |   {t['pdf_assets']}: {', '.join(tickers)}", ln=True, align="C")
    pdf.ln(8)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 30, 50)
    pdf.cell(0, 8, t["pdf_metrics"], ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    col_w = [35, 38, 28, 28, 30, 32]
    headers = [t["ticker_col"], t["ann_return_col"], t["volatility"], t["sharpe"], t["sortino"], t["max_dd"]]
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(20, 30, 60)
    pdf.set_text_color(200, 220, 255)
    for i, h in enumerate(headers):
        pdf.cell(col_w[i], 8, h, border=1, fill=True, align="C")
    pdf.ln()
    pdf.set_font("Helvetica", "", 9)
    for idx, row in metrics.iterrows():
        pdf.set_text_color(30, 30, 50)
        vals = [str(idx), f"{row['ann_return']:.1%}", f"{row['volatility']:.1%}", f"{row['sharpe']:.2f}", f"{row['sortino']:.2f}", f"{row['max_dd']:.1%}"]
        for i, v in enumerate(vals):
            pdf.cell(col_w[i], 7, v, border=1, align="C")
        pdf.ln()
    pdf.ln(8)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 30, 50)
    pdf.cell(0, 8, t["pdf_alloc"], ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "", 10)
    for ticker, w in weights.items():
        pdf.set_text_color(30, 30, 50)
        pdf.cell(40, 7, ticker, border=0)
        pdf.set_fill_color(77, 166, 255)
        bar_w = int(w * 120)
        pdf.cell(bar_w, 5, "", fill=True, border=0)
        pdf.set_text_color(80, 80, 100)
        pdf.cell(0, 7, f"  {w:.1%}", ln=True)
    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 30, 50)
    pdf.cell(0, 8, t["pdf_insights"], ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    for category, items in insights.items():
        if items:
            pdf.set_font("Helvetica", "B", 10)
            colors_map = {"increase": (0,160,120), "decrease": (200,40,70), "diversify": (50,100,200)}
            pdf.set_text_color(*colors_map[category])
            pdf.cell(0, 7, category.upper(), ln=True)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(50, 50, 70)
            for item in items:
                clean = item.replace("<b>", "").replace("</b>", "")
                pdf.multi_cell(0, 6, f"  - {clean}")
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(140, 140, 160)
    pdf.cell(0, 5, t["pdf_footer"], align="C")
    return pdf.output()

# ─── SIDEBAR ───
with st.sidebar:
    st.markdown('<div class="brand">⬡ QuantEdge</div>', unsafe_allow_html=True)

    # Language toggle
    lang = st.selectbox("", ["🇬🇧 English", "🇫🇷 Français"], label_visibility="collapsed")
    lang_code = "en" if "English" in lang else "fr"
    t = T[lang_code]

    st.markdown(f'<div class="brand-sub">{t["brand_sub"]}</div>', unsafe_allow_html=True)
    st.markdown("---")
    st.markdown(f"**{t['config']}**")
    tickers_raw = st.text_input(t["tickers"], value="AAPL, MSFT, GOOGL, AMZN, JPM")
    tickers = [x.strip().upper() for x in tickers_raw.split(",") if x.strip()]
    col1, col2 = st.columns(2)
    with col1:
        start_date = st.date_input(t["start"], value=date.today() - timedelta(days=3*365))
    with col2:
        end_date = st.date_input(t["end"], value=date.today())
    st.markdown("---")
    st.markdown(f"**{t['risk_params']}**")
    risk_tolerance = st.slider(t["risk_tolerance"], min_value=0.0, max_value=1.0, value=0.5, step=0.05)
    risk_label = t["conservative"] if risk_tolerance < 0.35 else (t["balanced"] if risk_tolerance < 0.65 else t["aggressive"])
    st.caption(f"{t['profile']}: **{risk_label}**")
    st.markdown("---")
    run_btn = st.button(t["run"], use_container_width=True)
    st.markdown("---")
    st.markdown(f'<div style="font-size:10px;color:#3a4a62;text-align:center;">{t["disclaimer"]}</div>', unsafe_allow_html=True)

# ─── MAIN ───
st.markdown(f'<div style="font-size:26px;font-weight:800;color:#e8eaf0;">{t["title"]}<span style="color:#4da6ff;font-weight:300;">{t["title2"]}</span></div>', unsafe_allow_html=True)
st.markdown("<hr>", unsafe_allow_html=True)

if not run_btn:
    st.markdown(f"""
    <div style="text-align:center;padding:80px 40px;">
        <div style="font-size:64px;">📊</div>
        <div style="font-size:22px;font-weight:600;color:#c9d1e0;margin:16px 0 8px;">{t["landing_title"]}</div>
        <div style="font-size:14px;color:#4a5568;">{t["landing_sub"]}</div>
    </div>
    """, unsafe_allow_html=True)
    st.stop()

with st.spinner(t["fetching"]):
    prices = download_data(tickers, str(start_date), str(end_date))

valid_tickers = [x for x in tickers if x in prices.columns]
if not valid_tickers:
    st.error(t["no_tickers"])
    st.stop()
if len(valid_tickers) < len(tickers):
    st.warning(f"{t['could_not_load']}: {', '.join(set(tickers)-set(valid_tickers))}")

prices = prices[valid_tickers].dropna()
metrics, returns, cum_returns, drawdown = compute_metrics(prices)
weights = optimize_portfolio(returns, risk_tolerance)
insights = generate_insights(metrics, returns, t)

# SECTION 1
st.markdown(f'<div class="section-header">{t["s1"]}</div>', unsafe_allow_html=True)
avg_return = metrics["ann_return"].mean()
avg_vol = metrics["volatility"].mean()
avg_sharpe = metrics["sharpe"].mean()
avg_sortino = metrics["sortino"].mean()
avg_dd = metrics["max_dd"].mean()
kpi_cols = st.columns(5)
kpis = [
    (t["ann_return"], f"{avg_return:.1%}", "positive" if avg_return > 0 else "negative"),
    (t["volatility"], f"{avg_vol:.1%}", "neutral"),
    (t["sharpe"], f"{avg_sharpe:.2f}", "positive" if avg_sharpe > 1 else "neutral"),
    (t["sortino"], f"{avg_sortino:.2f}", "positive" if avg_sortino > 1 else "neutral"),
    (t["max_dd"], f"{avg_dd:.1%}", "negative"),
]
for col, (label, val, cls) in zip(kpi_cols, kpis):
    with col:
        st.markdown(f'<div class="metric-card"><div class="metric-label">{label}</div><div class="metric-value {cls}">{val}</div></div>', unsafe_allow_html=True)
st.markdown("<br>", unsafe_allow_html=True)
fmt = metrics.copy()
fmt.columns = [t["ann_return"], t["volatility"], t["sharpe"], t["sortino"], t["max_dd"]]
for c in [t["ann_return"], t["volatility"], t["max_dd"]]: fmt[c] = fmt[c].map(lambda x: f"{x:.2%}")
for c in [t["sharpe"], t["sortino"]]: fmt[c] = fmt[c].map(lambda x: f"{x:.2f}")
st.dataframe(fmt, use_container_width=True)

# SECTION 2
st.markdown("<br>", unsafe_allow_html=True)
st.markdown(f'<div class="section-header">{t["s2"]}</div>', unsafe_allow_html=True)
r1, r2 = st.columns([1.1, 1])
with r1:
    corr = returns.corr()
    fig_corr = go.Figure(data=go.Heatmap(
        z=corr.values, x=corr.columns.tolist(), y=corr.index.tolist(),
        colorscale=[[0,"#1a0533"],[0.5,"#1e3a5f"],[1,"#00d4a0"]],
        zmin=-1, zmax=1, text=np.round(corr.values,2), texttemplate="%{text}",
        textfont=dict(size=11,color="white"), showscale=True
    ))
    fig_corr.update_layout(title=dict(text=t["corr_matrix"], font=dict(size=13,color="#4da6ff")), **CHART_LAYOUT)
    st.plotly_chart(fig_corr, use_container_width=True)
with r2:
    scatter_data = pd.DataFrame({"x": metrics["volatility"], "y": metrics["ann_return"], "s": metrics["sharpe"], "Ticker": metrics.index})
    fig_scatter = px.scatter(scatter_data, x="x", y="y", color="s", text="Ticker",
    color_continuous_scale="Viridis",
    labels={"x": t["volatility"], "y": t["ann_return"], "s": t["sharpe"]})
    fig_scatter.update_traces(textposition="top center", textfont=dict(size=11,color="#e8eaf0"))
    fig_scatter.update_layout(title=dict(text=t["ret_vol"], font=dict(size=13,color="#4da6ff")), **CHART_LAYOUT)
    st.plotly_chart(fig_scatter, use_container_width=True)

# SECTION 3
st.markdown(f'<div class="section-header">{t["s3"]}</div>', unsafe_allow_html=True)
colors = ["#4da6ff","#00d4a0","#ff4d6d","#ffd166","#a78bfa","#f97316","#38bdf8"]
fig_cum = go.Figure()
for i, ticker in enumerate(valid_tickers):
    fig_cum.add_trace(go.Scatter(x=cum_returns.index, y=cum_returns[ticker], name=ticker, line=dict(color=colors[i%len(colors)],width=2)))
fig_cum.update_layout(title=dict(text=t["cum_returns"], font=dict(size=13,color="#4da6ff")), yaxis_title=t["growth"], **CHART_LAYOUT)
st.plotly_chart(fig_cum, use_container_width=True)
fig_dd = go.Figure()
for i, ticker in enumerate(valid_tickers):
    fig_dd.add_trace(go.Scatter(x=drawdown.index, y=drawdown[ticker], name=ticker, fill="tozeroy", line=dict(color=colors[i%len(colors)],width=1.5)))
fig_dd.update_layout(title=dict(text=t["drawdown"], font=dict(size=13,color="#4da6ff")), yaxis_tickformat=".0%", **CHART_LAYOUT)
st.plotly_chart(fig_dd, use_container_width=True)

# SECTION 4
st.markdown(f'<div class="section-header">{t["s4"]}</div>', unsafe_allow_html=True)
o1, o2 = st.columns([1,1.4])
with o1:
    weight_df = pd.DataFrame({t["weight"]: [f"{w:.1%}" for w in weights.values()], t["alloc_10k"]: [f"${w*10000:,.0f}" for w in weights.values()]}, index=weights.keys())
    st.dataframe(weight_df, use_container_width=True)
with o2:
    fig_pie = go.Figure(data=go.Pie(
        labels=list(weights.keys()), values=list(weights.values()), hole=0.55,
        marker=dict(colors=colors[:len(weights)], line=dict(color="#0a0e1a",width=3)),
        textinfo="label+percent", textfont=dict(size=12,color="white")
    ))
    fig_pie.update_layout(paper_bgcolor="#111827", plot_bgcolor="#111827", font=dict(color="#c9d1e0"),
        showlegend=True, legend=dict(font=dict(color="#c9d1e0"),bgcolor="rgba(0,0,0,0)"),
        margin=dict(l=20,r=20,t=50,b=20), title=dict(text=t["opt_alloc"],font=dict(size=13,color="#4da6ff")))
    st.plotly_chart(fig_pie, use_container_width=True)

# SECTION 5
st.markdown(f'<div class="section-header">{t["s5"]}</div>', unsafe_allow_html=True)
i1, i2, i3 = st.columns(3)
with i1:
    st.markdown(f"**{t['increase']}**")
    if insights["increase"]:
        for item in insights["increase"]:
            st.markdown(f'<div class="insight-increase">{item}</div>', unsafe_allow_html=True)
    else:
        st.markdown(f'<div class="insight-diversify">{t["no_increase"]}</div>', unsafe_allow_html=True)
with i2:
    st.markdown(f"**{t['decrease']}**")
    if insights["decrease"]:
        for item in insights["decrease"]:
            st.markdown(f'<div class="insight-decrease">{item}</div>', unsafe_allow_html=True)
    else:
        st.markdown(f'<div class="insight-diversify">{t["no_decrease"]}</div>', unsafe_allow_html=True)
with i3:
    st.markdown(f"**{t['diversify']}**")
    if insights["diversify"]:
        for item in insights["diversify"]:
            st.markdown(f'<div class="insight-diversify">{item}</div>', unsafe_allow_html=True)
    else:
        st.markdown(f'<div class="insight-diversify">{t["no_diversify"]}</div>', unsafe_allow_html=True)

# SECTION 6
st.markdown("<br>", unsafe_allow_html=True)
st.markdown(f'<div class="section-header">{t["s6"]}</div>', unsafe_allow_html=True)
_, pc, _ = st.columns([1,2,1])
with pc:
    if st.button(t["download_pdf"], use_container_width=True):
        with st.spinner(t["generating_pdf"]):
            pdf_bytes = make_pdf_report(valid_tickers, str(start_date), str(end_date), metrics, weights, insights, t)
        if pdf_bytes:
            b64 = base64.b64encode(pdf_bytes).decode()
            fname = f"QuantEdge_Report_{date.today().strftime('%Y%m%d')}.pdf"
            st.markdown(f'<a href="data:application/pdf;base64,{b64}" download="{fname}"><button style="background:linear-gradient(135deg,#1a4fa0,#0d2d6b);color:white;border:none;border-radius:8px;padding:12px 24px;font-size:14px;font-weight:600;cursor:pointer;width:100%;">{t["save_pdf"]}</button></a>', unsafe_allow_html=True)
        else:
            st.error(t["pdf_failed"])

st.markdown(f'<div style="text-align:center;padding:20px 0;font-size:10px;color:#1e2535;">{t["footer"]}</div>', unsafe_allow_html=True)
